/*
 FreeRTOS.org V5.3.0 - Copyright (C) 2003-2009 Richard Barry.

 This file is part of the FreeRTOS.org distribution.

 FreeRTOS.org is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License (version 2) as published
 by the Free Software Foundation and modified by the FreeRTOS exception.
 **NOTE** The exception to the GPL is included to allow you to distribute a
 combined work that includes FreeRTOS.org without being obliged to provide
 the source code for any proprietary components.  Alternative commercial
 license and support terms are also available upon request.  See the
 licensing section of http://www.FreeRTOS.org for full details.

 FreeRTOS.org is distributed in the hope that it will be useful,	but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 more details.

 You should have received a copy of the GNU General Public License along
 with FreeRTOS.org; if not, write to the Free Software Foundation, Inc., 59
 Temple Place, Suite 330, Boston, MA  02111-1307  USA.


 ***************************************************************************
 *                                                                         *
 * Get the FreeRTOS eBook!  See http://www.FreeRTOS.org/Documentation      *
 *                                                                         *
 * This is a concise, step by step, 'hands on' guide that describes both   *
 * general multitasking concepts and FreeRTOS specifics. It presents and   *
 * explains numerous examples that are written using the FreeRTOS API.     *
 * Full source code for all the examples is provided in an accompanying    *
 * .zip file.                                                              *
 *                                                                         *
 ***************************************************************************

 1 tab == 4 spaces!

 Please ensure to read the configuration and relevant port sections of the
 online documentation.

 http://www.FreeRTOS.org - Documentation, latest information, license and
 contact details.

 http://www.SafeRTOS.com - A version that is certified for use in safety
 critical systems.

 http://www.OpenRTOS.com - Commercial support, development, porting,
 licensing and training services.
 */

#ifndef FREERTOS_CONFIG_H
#define FREERTOS_CONFIG_H

#include <avr/io.h>

/*-----------------------------------------------------------
 * Application specific definitions.
 *
 * These definitions should be adjusted for your particular hardware and
 * application requirements.
 *
 * For each atmega or attiny chip have a file, you can reutilizes a existent
 * or create a new.
 *
 * THESE PARAMETERS ARE DESCRIBED WITHIN THE 'CONFIGURATION' SECTION OF THE
 * FreeRTOS API DOCUMENTATION AVAILABLE ON THE FreeRTOS.org WEB SITE.
 *
 * See http://www.freertos.org/a00110.html.
 *----------------------------------------------------------*/

#ifndef FREERTOS_ARDUINO
#define FREERTOS_ARDUINO 1
#endif


/*
 * The list structure members are modified from within interrupts, and therefore
 * by rights should be declared volatile.  However, they are only modified in a
 * functionally atomic way (within critical sections of with the scheduler
 * suspended) and are either passed by reference into a function or indexed via
 * a volatile variable.  Therefore, in all use cases tested so far, the volatile
 * qualifier can be omitted in order to provide a moderate performance
 * improvement without adversely affecting functional behaviour.  The assembly
 * instructions generated by the IAR, ARM and GCC compilers when the respective
 * compiler's options were set for maximum optimisation has been inspected and
 * deemed to be as intended.  That said, as compiler technology advances, and
 * especially if aggressive cross module optimisation is used (a use case that
 * has not been exercised to any great extend) then it is feasible that the
 * volatile qualifier will be needed for correct optimisation.  It is expected
 * that a compiler removing essential code because, without the volatile
 * qualifier on the list structure members and with aggressive cross module
 * optimisation, the compiler deemed the code unnecessary will result in
 * complete and obvious failure of the scheduler.  If this is ever experienced
 * then the volatile qualifier can be inserted in the relevant places within the
 * list structures by simply defining configLIST_VOLATILE to volatile in
 * FreeRTOSConfig.h (as per the example at the bottom of this comment block).
 * If configLIST_VOLATILE is not defined then the preprocessor directives below
 * will simply #define configLIST_VOLATILE away completely.
 *
 * To use volatile list structure members then add the following line to
 * FreeRTOSConfig.h (without the quotes):
 * "#define configLIST_VOLATILE volatile"
 */
#define configLIST_VOLATILE volatile

#if defined(__AVR_ATmega644__) || defined(__AVR_ATmega644P__)
#include "FreeRTOSConfigATmega644.h"

#elif defined(__AVR_ATmega1284P__)
#include "FreeRTOSConfigATmega1284P.h"

#elif defined(__AVR_ATmega1280__)
#include "FreeRTOSConfigATmega1280.h"

#elif defined(__AVR_ATmega2560__)
#include "FreeRTOSConfigATmega2560.h"

#elif defined(__AVR_ATmega328P__)
#include "FreeRTOSConfigATmega328P.h"

#elif defined(__AVR_ATmega88__) || defined(__AVR_ATmega88P__) || defined(__AVR_ATmega168__) || defined(__AVR_ATmega168P__)
#include "FreeRTOSConfigATmega168P.h"
#else
#error "Device is not supported by DuinOS"

#endif

#ifndef configUSE_PREEMPTION
#define configUSE_PREEMPTION		1
#endif

#ifndef configUSE_IDLE_HOOK
#define configUSE_IDLE_HOOK			0
#endif

#ifndef configUSE_TICK_HOOK
#define configUSE_TICK_HOOK			1
#endif

#ifndef configCPU_CLOCK_HZ
#define configCPU_CLOCK_HZ			( ( unsigned portLONG ) F_CPU )
#endif

#ifndef configTICK_RATE_HZ
#define configTICK_RATE_HZ			( ( portTickType ) 1000 )
#endif

#ifndef configMAX_PRIORITIES
#define configMAX_PRIORITIES		( ( unsigned portBASE_TYPE ) 3 )
#endif

	/* setup() and loop() parameters */
#ifndef configSETUP_STACK_SIZE
	#define configSETUP_STACK_SIZE          (configMINIMAL_STACK_SIZE)
#endif
#ifndef configLOOP_STACK_SIZE
	#define configLOOP_STACK_SIZE           (configMINIMAL_STACK_SIZE)
#endif
#ifndef configSETUP_PRIORITY
	#define configSETUP_PRIORITY			HIGH_PRIORITY
#endif
#ifndef configLOOP_PRIORITY
	#define configLOOP_PRIORITY				LOW_PRIORITY
#endif

#if INCLUDE_vTaskDelete == 1
#define CONFIG_HEAP_MODEL 2
#else
#define CONFIG_HEAP_MODEL 1
#endif

#endif /* FREERTOS_CONFIG_H */
